Config.Aduties = {
    projektleitung = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 2,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 2,
            ['shoes_1'] = 78, ['shoes_2'] = 2,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 2,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 2,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 2,
            ['shoes_1'] = 82, ['shoes_2'] = 2,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 153, ['mask_2'] = 2,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    },
    teamverwaltung = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 3,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 3,
            ['shoes_1'] = 78, ['shoes_2'] = 3,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 3,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 2,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 2,
            ['shoes_1'] = 82, ['shoes_2'] = 2,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 153, ['mask_2'] = 2,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    },
    stv = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 1,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 1,
            ['shoes_1'] = 78, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 1,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 3,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 3,
            ['shoes_1'] = 82, ['shoes_2'] = 3,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 153, ['mask_2'] = 3,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    },
    manager = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 11,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 11,
            ['shoes_1'] = 78, ['shoes_2'] = 11,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 11,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 3,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 3,
            ['shoes_1'] = 82, ['shoes_2'] = 3,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 153, ['mask_2'] = 3,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    },
    headadmin = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 12,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 12,
            ['shoes_1'] = 78, ['shoes_2'] = 12,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 12,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 12,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 12,
            ['shoes_1'] = 72, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 12,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    },
    admin = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 6,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 6,
            ['shoes_1'] = 78, ['shoes_2'] = 6,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 6,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 6,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 6,
            ['shoes_1'] = 72, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 6,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    },
    supportleitung = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 0,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 0,
            ['shoes_1'] = 78, ['shoes_2'] = 0,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 0,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 0,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 0,
            ['shoes_1'] = 72, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 0,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    },
    entwickler = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 8,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 8,
            ['shoes_1'] = 78, ['shoes_2'] = 8,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 8,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 8,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 8,
            ['shoes_1'] = 72, ['shoes_2'] = 1,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 8,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    },
    mod = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 4,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 4,
            ['shoes_1'] = 78, ['shoes_2'] = 4,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 4,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 4,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 4,
            ['shoes_1'] = 72, ['shoes_2'] = 4,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 4,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    },
    supporter = {
        [0] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 287, ['torso_2'] = 5,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114, ['pants_2'] = 5,
            ['shoes_1'] = 78, ['shoes_2'] = 5,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 5,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        },
        [1] = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 300, ['torso_2'] = 5,
            ['decals_1'] = 0, ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121, ['pants_2'] = 5,
            ['shoes_1'] = 72, ['shoes_2'] = 5,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['mask_1'] = 135, ['mask_2'] = 5,
            ['chain_1'] = 0, ['chain_2'] = 0,
            ['ears_1'] = 0, ['ears_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
            ['hair_1'] = 0, ['hair_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0
        }
    }    
}